services:
  build:
    build:
      network: none
    cap_drop:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT

    command: ["run", "clean-verify"]
    entrypoint: ["npm"]
    networks: ["node"]
    security_opt: ["no-new-privileges:true"]
    volumes:
      # Bind the current directory to the working directory inside the container.
      - type: "bind"
        source: "./"
        target: "/app"

      # Rename "docker.npmrc" to ".npmrc"
      - type: "bind"
        source: "./docker.npmrc"
        target: "/app/.npmrc"

      # Bind the NPM cache.
      - "~/.npm/_cacache:/tmp/npm-cache/_cacache"

      # Use higher performance volumes for intermediate directories.
      - type: "volume"
        source: build_rollup
        target: "/app/build/rollup"
      - type: "volume"
        source: build_typescript
        target: "/app/build/typescript"
      - type: "volume"
        source: node_modules
        target: "/app/node_modules"

    working_dir: "/app"

networks:
  node:

volumes:
  build_rollup:
  build_typescript:
  node_modules: