services:
  npm:
    build:
      context: "./images/npm"
      network: host
    cap_drop: ["ALL"]
    command: ["run", "clean-verify"]
    entrypoint: ["npm"]
    environment:
      MINISIGN_CONFIG_DIR: /run/secrets
    network_mode: "host"
    secrets:
      - source: minisign
        target: "minisign.key"

    security_opt: ["no-new-privileges:true"]
    volumes:
      # Bind the current directory to the working directory inside the container.
      - type: "bind"
        source: "./"
        target: "/app"

      # Rename "docker.npmrc" to ".npmrc"
      - type: "bind"
        read_only: true
        source: "./docker.npmrc"
        target: "/app/.npmrc"

      # Bind the NPM cache.
      - type: "bind"
        source: "~/.npm/_cacache"
        target: "/tmp/npm-cache/_cacache"
        bind:
          create_host_path: true
      
      # Prepare build directory.
      - type: "bind"
        source: "./build"
        target: "/app/build"
        bind:
          create_host_path: true

      # Use higher performance volumes for intermediate directories.
      - type: "volume"
        source: build_rollup
        target: "/app/build/rollup"
      - type: "volume"
        source: build_typescript
        target: "/app/build/typescript"
      - type: "volume"
        source: node_modules
        target: "/app/node_modules"
    
    working_dir: "/app"

secrets:
   minisign:
    file: "${MINISIGN_KEY_PATH:-/dev/null}"

volumes:
  build_rollup:
  build_typescript:
  node_modules: