#!/bin/sh

COMPOSE_ENGINE='docker compose';

# Parse options
while [ $# -gt 0 ]; do
    case $1 in
        --docker)
            COMPOSE_ENGINE='docker compose'
            ;;
        --docker-compose)
            COMPOSE_ENGINE='docker-compose'
            ;;
        --podman)
            COMPOSE_ENGINE='podman compose'
            ;;
        --podman-compose)
            COMPOSE_ENGINE='podman-compose'
            ;;
        --)
            shift;
            break;
            ;;
        -*)
            printf 'Unknown option %s\n' $1 >&2;
            exit 1;
            ;;
        *)
            break;
            ;;
    esac
    shift;
done

./user-mirror $COMPOSE_ENGINE build
./user-mirror $COMPOSE_ENGINE run --rm npm "$@"