#!/bin/sh

# This script starts a temporary docker container, then forwards all the script arguments to it.

DOCKER_IMAGE=node:20.3.1-alpine

# Start, or restart docker if not running
docker version >/dev/null 2>&1
if [ $? -ne 0 ]; then
    echo 1
    service docker status >/dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo 2
        sudo service docker start
    else
        echo 3
        sudo service docker restart
    fi

    docker version >/dev/null 2>&1
    while [ $? -ne 0 ]; do
        sleep 1
        docker version >/dev/null 2>&1
    done
fi

container_exec() {
    script_dir=$(cd -- "$(dirname -- "$0")" && pwd)
    docker run -it --rm --mount "type=bind,source=$script_dir,target=/app" --workdir /app $DOCKER_IMAGE $@
}

if [ $# -eq 0 ]; then
    container_exec npm run default
else
    container_exec $@
fi