#!/bin/sh
## DESCRIPTION
#|   Launch a watch build, and serve live edits of the built script. The script
#|     will be located at http://localhost:8080/script.user.js
#|     https://violentmonkey.github.io/posts/how-to-edit-scripts-with-your-favorite-editor/#install-a-local-script

COMPOSE_FILE='docker-compose.watch-build-server.yml'

if  docker info -f '{{println .SecurityOptions}}' | grep 'rootless' 1>/dev/null; then
    (docker compose --file "$COMPOSE_FILE" build watch-build server \
    )
else
    (docker compose --file "$COMPOSE_FILE" build \
        --build-arg "USER_ID=$(id -u)" \
        --build-arg "USER_NAME=$(id -un)" \
        --build-arg "USER_GROUP_ID=$(id -g)" \
        --build-arg "USER_GROUP_NAME=$(id -gn)" \
        watch-build server \
    )
fi

# Ignore Ctrl+C
trap '' INT TSTP

docker compose --file "$COMPOSE_FILE" up --no-log-prefix
docker compose --file "$COMPOSE_FILE" down