#!/bin/sh
## DESCRIPTION
#|   Launch a watch build, and serve live edits of the built script. The script
#|     will be located at http://localhost:8080/script.user.js
#|     https://violentmonkey.github.io/posts/how-to-edit-scripts-with-your-favorite-editor/#install-a-local-script

COMPOSE_FILE='docker-compose.watch-build-server.yml'
COMPOSE_ENGINE='docker compose';
CONTAINER_ENGINE='docker';

# Parse options
while [ $# -gt 0 ]; do
    case $1 in
        --docker)
            COMPOSE_ENGINE='docker compose';
            CONTAINER_ENGINE='docker';
            ;;
        --docker-compose)
            COMPOSE_ENGINE='docker-compose';
            CONTAINER_ENGINE='docker';
            ;;
        --podman)
            COMPOSE_ENGINE='podman compose';
            CONTAINER_ENGINE='podman';
            ;;
        --podman-compose)
            COMPOSE_ENGINE='podman-compose';
            CONTAINER_ENGINE='podman';
            ;;
        --)
            shift;
            break;
            ;;
        -*)
            printf 'Unknown option %s\n' $1 >&2;
            exit 1;
            ;;
        *)
            break;
            ;;
    esac
    shift;
done

$COMPOSE_ENGINE --file "$COMPOSE_FILE" build watch-build server;

if [ "$CONTAINER_ENGINE" = "podman" ] || docker info -f '{{println .SecurityOptions}}' | grep 'rootless' 1>/dev/null; then
    echo 'GID=0' >> watch-build-server.env;
    echo 'GROUP=root' >> watch-build-server.env;
    echo 'UID=0' >> watch-build-server.env;
    echo 'USER=root' >> watch-build-server.env;
else
    echo "GID=$(id -g)" >> watch-build-server.env;
    echo "GROUP=$(id -gn)" >> watch-build-server.env;
    echo "UID=$(id -u)" >> watch-build-server.env;
    echo "USER=$(id -un)" >> watch-build-server.env;
fi

# Ignore Ctrl+C
trap '' INT TSTP;

./user-mirror $COMPOSE_ENGINE --env-file watch-build-server.env --file "$COMPOSE_FILE" up --no-log-prefix;
rm watch-build-server.env;
$COMPOSE_ENGINE --file "$COMPOSE_FILE" down;