# This workflow is used for continuous integration verification, and storing the resulting build artifacts.

name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
      - "!dependabot/**"
    paths:
      - "**"
      - "!*.md"
      - "!.github/**"
      - ".github/workflows/*.yml"
      - "!.github/workflows/cd.yml"
  pull_request:
    branches:
      - "**"
    paths:
      - "**"
      - "!*.md"
      - "!.github/**"
      - ".github/workflows/*.yml"
      - "!.github/workflows/cd.yml"

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker-context: ["rootless", "default"]

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Use Rootless Docker
      if: ${{ matrix.docker-context == 'rootless' }}
      uses: ScribeMD/rootless-docker@6bd157a512c2fafa4e0243a8aa87d964eb890886 # 0.2.2

    - name: "Validate Docker Compose Files"
      run: |
        docker compose --file docker-compose.yml config --quiet
        docker compose --file docker-compose.watch-build-server.yml config --quiet

    - name: "Docker Cache"
      id: docker-cache
      uses: ScribeMD/docker-cache@e481e638abdb45e2fa30845305c387a544cc617f # 0.3.7
      with:
        key: docker-${{ runner.os }}-${{ hashFiles('./Dockerfile', './images/yq/Dockerfile') }}
    
    - name: "NPM Cache"
      id: npm-cache
      uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
      with:
        path: "~/.npm/_cacache"
        key: npm-${{ runner.os }}-${{ hashFiles('./package-lock.json') }}

    - name: "Build and Verify"
      run: |
        chmod +x "./toolbox"
        ./toolbox -- run clean-verify

    - name: "Upload Artifacts"
      if: ${{ matrix.docker-context == 'rootless' }}
      uses: actions/upload-artifact@1eb3cb2b3e0f29609092a73eb033bb759a334595 # v4.1.0
      with:
        name: artifacts
        path: build/release/
        if-no-files-found: error
