# This workflow is used for continuous integration verification, and storing the resulting build artifacts.

name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
      - "!dependabot/**"
    paths:
      - "**"
      - "!*.md"
      - "!.github/**"
      - ".github/workflows/*.yml"
      - "!.github/workflows/cd.yml"
  pull_request:
    branches:
      - "**"
    paths:
      - "**"
      - "!*.md"
      - "!.github/**"
      - ".github/workflows/*.yml"
      - "!.github/workflows/cd.yml"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: "Extract Docker Images"
      run: docker compose config --images | uniq > /tmp/docker-compose.yml.images

    - name: "Docker Cache"
      uses: ScribeMD/docker-cache@0.3.3
      with:
        key: docker-${{ runner.os }}-${{ hashFiles('./tmp/docker-compose.yml.images') }}
    
    - name: "NPM Cache"
      id: npm-cache
      uses: actions/cache@v3
      with:
        path: "~/.npm/_cacache"
        key: npm-${{ runner.os }}-${{ hashFiles('./package-lock.json') }}

    - name: "Build and Verify"
      run: |
        chmod +x "./toolbox"
        ./toolbox -- run clean-verify

    - name: "Upload artifacts"
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: build/release/
        if-no-files-found: error
    
    - name: Verify Cache
      if: ${{ steps.npm-cache.outputs.cache-hit != 'true' }}
      run: ./toolbox -- cache verify
