# This workflow is used for continuous integration verification, and storing the resulting build artifacts.

name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
      - "!dependabot/**"
    paths:
      - "**"
      - "!*.md"
      - "!.github/**"
      - ".github/workflows/*.yml"
      - "!.github/workflows/cd.yml"
  pull_request:
    branches:
      - "**"
    paths:
      - "**"
      - "!*.md"
      - "!.github/**"
      - ".github/workflows/*.yml"
      - "!.github/workflows/cd.yml"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Rootless Docker
      uses: ScribeMD/rootless-docker@0.2.2

    - name: "Validate Docker Compose Files"
      run: |
        docker compose --file docker-compose.yml config --quiet
        docker compose --file docker-compose.watch-build-server.yml config --quiet

    - name: "Docker Cache"
      id: docker-cache
      uses: ScribeMD/docker-cache@0.3.3
      with:
        key: docker-${{ runner.os }}-${{ hashFiles('./Dockerfile') }}
        restore-keys: |
          docker-${{ runner.os }}-
    
    - name: "NPM Cache"
      id: npm-cache
      uses: actions/cache@v3
      with:
        path: "~/.npm/_cacache"
        key: npm-${{ runner.os }}-${{ hashFiles('./package-lock.json') }}
        restore-keys: |
          npm-${{ runner.os }}-

    - name: "Build and Verify"
      run: |
        chmod +x "./toolbox"
        ./toolbox -- run clean-verify

    - name: "Upload Artifacts"
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: build/release/
        if-no-files-found: error
    
    - name: Clean NPM Cache
      if: ${{ steps.npm-cache.outputs.cache-hit != 'true' }}
      run: ./toolbox -- cache verify

    - name: Clean Docker Cache
      if: ${{ steps.docker-cache.outputs.cache-hit != 'true' }}
      run: docker image prune -f
