# This workflow is used for continuous integration verification, and storing the resulting build artifacts.

name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - "**"
      - "!*.md"
      - "!.github/**"
      - ".github/workflows/*.yml"
      - "!.github/workflows/cd.yml"
  pull_request:
    branches:
      - '**'
    paths:
      - "**"
      - "!*.md"
      - "!.github/**"
      - ".github/workflows/*.yml"
      - "!.github/workflows/cd.yml"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: "Build and Verify"
      run: |
        chmod +x "./toolchain"
        sh ./toolchain npm run verify

    - name: "Upload artifacts"
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: build/release/
        if-no-files-found: error
