# This workflow is used for continuous integration verification, and storing the resulting build artifacts.

name: Continuous Integration

on:
  push:
    branches: [mainline]
    paths-ignore:
      - "*.md"
      - ".github/workflows/cd.yml"
  pull_request:
    branches: [mainline]
    paths-ignore:
      - "*.md"
      - ".github/workflows/cd.yml"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.3.1
        cache: "npm"

    - name: "Install dependencies"
      run: npm run install:clean

    - name: "Pre-build Verification"
      run: npm run verify:pre-build

    - name: "Build"
      run: npm run build

    - name: "Post-build Verification"
      run: npm run verify:post-build

    - name: "Upload artifacts"
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: build/release/
        if-no-files-found: error