name: Publish wiki
on:
  push:
    branches: [mainline]
    paths:
      - .github/wiki/**
      - .github/workflows/wiki.yml

concurrency:
  group: wiki
  cancel-in-progress: true

permissions: {}

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: Andrew-Chen-Wang/github-wiki-action@50650fccf3a10f741995523cf9708c53cec8912a # v4.4.0
        with:
            path: .github/wiki/