name: Publish wiki
on:
  push:
    branches: [mainline]
    paths:
      - .github/wiki/**
      - .github/workflows/wiki.yml

concurrency:
  group: wiki
  cancel-in-progress: true

permissions: {}

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: Andrew-Chen-Wang/github-wiki-action@50650fccf3a10f741995523cf9708c53cec8912a # v4.4.0
        with:
            path: .github/wiki/